### ISSUE TITLE
Kész számológép

### ISSUE THREAD

**Issue by illesgabor1126** [Teaching-projects/SOE-ProgAlap2-Beadando-Calculator#4]

**Comment by hegyhati** [comment]
UI:

- [ ] Amikor potyogok, akkor az mindig hozzafuz a fent levokhoz, ami nem az intuitiv mukodes. Az az volna, hogyha elkezdek gepelni akkor, amikor nem szamot var, akkor kitorli azt, ami van.
- [ ] Ha benyomkodom, hogy 4  *4 *4= akkor kijon, hogy 16.
- [ ] par dologgal, pl 0-val osztas, ki lehet akasztani, de ilyenkor csak a konzolban latszodik hibauzenet, ezek jo lennenek, ha a feluleten megjelennenek.
- [ ] A datumszamitoba tok fals adatokat beirva (34/34/34, 34/12/34), olyan eredmenyeket kapok, hogy 0-1/0-10/00 
- [ ] Amiknel nincs ertelme, hogy szerkeszthessem (pl atvaltonal az eredmenyke, azok ne legyenek szerkeszthetoek. 

Kod:

- [ ] Jol sejtem, hogy most duplikaltan megvan a kod? Marmint az egyik valtozat a `calculator.py`, a masik pedig a szetszedett? Egy repoban egy kodvaltozat eljen, ami mar nem aktualis, az legyen torolve.
- [ ] Nem jo practice az, hogy az egyes muveleteket azonositoszammal jegyezteted meg. Hogy minek mi az azonositoja, arra emlekeznie kell a logika oldalnak, es a felulet oldalnak. Es ha a ketto elmaszik egymas mellol, akkor abbol baj lesz. 
- [ ] Nem ertheto a kod. Logic osztalyt kezdtem el olvasni, nem tudom, mi az a current, f_num, second_number, meg number, es miert csinalunk belole egy objektumot. 
- [ ] Ezutan mindenhol a self.e-t piszkaljuk, de nem latom, hogy mi az, es hol lett beallitva.
- [ ] logikaban egy "button_click"  fuggveny gyanus, hogy nem okes, az nem tudhat semmit a feluletrol, de az sem vilagos, hogy miert specialis eset a 10?
- [ ] A gui reszben csak az inicializalas van, egy csomo mindennek meg itt lenne a helye, nem a logikaban.
- [ ] Szinten gui: amikor 10 egymas alatti sorban meglatom ugyanazt 1-1 karakter elteressel, akkor az ciklusert kialt.

A mukodes a bugokat eltekintve dicseretes, tetszik, hogy frame-eket hasznalsz, ugyes! Viszont a kodszervezesed nem jo. Most Te meg igy atlatod, ket het mulva mar lehet Te sem, es mas sem valoszinu. Ekkora projektnel meg ez elmegy, "izombol" megoldottad. Ha jegyet kell mondanom, akkor jelenleg 3, de en orulnek, ha rendbetenned, es tanulnal, fejlodnel belole. Ha szoftverfejleszto iranyban gondolkodsz, akkor ez elobb-utobb muszaj lesz.

**Comment by hegyhati** [comment]
Modositas nelkul akkor 3 a vegleges.
